# Generated by Django 3.2.7 on 2022-03-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital_affiliation',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
