# Generated by Django 3.2.7 on 2022-03-20 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20220320_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='doctor_id',
            new_name='doctor',
        ),
    ]
