# Generated by Django 3.2.7 on 2022-03-26 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_doctor_id_office_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='office_id',
            new_name='office',
        ),
    ]
